### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by amgno** [farfalleflickan/cmyflix#2]

**Comment by farfalleflickan** [comment]
I personally don't really see the point, as cmyflix isn't a webapp or a server, so it would just end up being a Docker image with Nginx paired with inotifywait to run cmyflix when your folders update. I feel it would be easier to just do that to begin with instead of adding complexity with Docker.

That being said, if you or anyone else writes a Dockerfile I would have nothing against adding it to the repo.

**Comment by starnakin** [comment]
#4
