### ISSUE TITLE
Use library that detects filenames

### ISSUE THREAD

**Issue by asakura42** [farfalleflickan/cmyflix#5]
Great program! I looked a lot for something such straightforward and simple but the last paragraph in the README gave me goosebumps: in 2024 we have many utilities and libraries to guess title, season, codec and anything. I know couple:

https://github.com/guessit-io/guessit - python library that works nice
https://github.com/lowlighter/rakun - something for anime
https://github.com/erengy/anitomy - well-designed cxx library for parsing anime filenames
https://github.com/platelminto/parse-torrent-title - python again, looks like guessit

What do you think?

**Comment by farfalleflickan** [comment]
For starters, no such library exists for C. So one would need to implement it all (which I am not inclined to do, cmyflix has decent enough filename parsing and supports using custom regexes anyway - the defaults provided in the configuration should work well enough).

If your issue is with the folder structure requirements, they are really mostly for TV shows and are key to the really fast performance of cmyflix. 

Technically it could support just a folder with everything dumped into it but I honestly don't see the point - it would also require some extensive re-writing and re-design. 

On top of all of this, properly formatted files/file structures are encouraged on other similar programs such as Jellyfin/Emby/Plex anyway. Yes, with cmyflix it is basically a requirement but I don't think it is an egregious one.

**Comment by asakura42** [comment]
Despite the issue is closed, I tried to find some solution - and found some tools that may be useful with renaming media if someone wants to use cmyflix but doesn't want to deal with manual renaming:
1. Filebot - exists in Arch AUR (foss version - `filebot47`) and had free license formerly - now it is proprietary, but there are still some free forks from the old days (https://github.com/mobeigi/filebot etc)
2. mnamer - https://github.com/jkwill87/mnamer - commandline tool that can rename media, look titles with guessit and so on
3. tvmv - https://github.com/keithfancher/tvmv - looks like it works only with TV shows but anyway

**Comment by farfalleflickan** [comment]
The easiest solution would be to use rename with a regex like this:
`rename -n 's/(?<=[sS][0-9]{2}[eE][0-9]{2})(..+(?=.mp4|.srt|.mkv))//g' **/*` 
That would transform all files that are `mp4`, `srt` or `mkv` recursively with the following result:
`Show.s01e01.Other.Words-in.File.name.mp4 -> Show.s01e01.mp4`
